version: "3.9"
services:
  db:
    image: postgres:16
    container_name: pg-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres2024
      POSTGRES_DB: myapp_db
    ports:
      - "1234:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin2024
    depends_on:
      - db

  mongodb:
    image: mongo:latest
    container_name: message_mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=mongoadmin2024
      - MONGO_INITDB_DATABASE=messageDB
    restart: always
